spring:
  profiles: 
    active: 
    - dev

---

server: 
  port: 8180
spring:
  profiles: test
  application: 
    name: service-test-config

---
server: 
  port: 8280
spring:
  profiles: dev
  application: 
    name: service-dev-config